# -*- coding: utf-8 -*-
"""CodeWirePro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9jPt0vQhDYcT_BGeDWHIfysCv4mVkwm

# **Codewire** - Portfolio Showcase Edition
"""

pip install gradio plotly reportlab pandas

import gradio as gr
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# ==========================================================
# GLOBAL STORAGE
# ==========================================================

projects = {}

# ==========================================================
# HEALTH SCORE ENGINE
# ==========================================================

def calculate_score(voltage_drop_percent):

    score = max(
        0,
        min(
            100,
            100 - (voltage_drop_percent * 8)
        )
    )

    if score >= 90:
        status = "PASS"
    elif score >= 70:
        status = "WARNING"
    else:
        status = "FAIL"

    return round(score), status

# ==========================================================
# KPI GENERATOR
# ==========================================================

def generate_kpi_cards(score=94, status="PASS", wire="10 AWG", drop="1.8%"):

    status_class = {
        "PASS": "status-pass",
        "WARNING": "status-warn",
        "FAIL": "status-fail"
    }.get(status, "status-pass")

    return f"""
    <div class="kpi-grid">

        <div class="kpi-card">
            <span class="kpi-icon">🛡️</span>
            <h2>{score}</h2>
            <p>Health Score</p>
        </div>

        <div class="kpi-card {status_class}">
            <span class="kpi-icon">✅</span>
            <h2>{status}</h2>
            <p>Compliance</p>
        </div>

        <div class="kpi-card">
            <span class="kpi-icon">🔌</span>
            <h2>{wire}</h2>
            <p>Recommended Wire</p>
        </div>

        <div class="kpi-card">
            <span class="kpi-icon">⚡</span>
            <h2>{drop}</h2>
            <p>Voltage Drop</p>
        </div>

    </div>
    """

# ==========================================================
# HEALTH GAUGE
# ==========================================================

def create_health_gauge(score=94):

    fig = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=score,
            title={"text": "Engineering Health"},
            gauge={"axis": {"range": [0, 100]}}
        )
    )

    fig.update_layout(
        template="plotly_dark",
        height=350
    )

    return fig

# ==========================================================
# CSS
# ==========================================================

css = """

.gradio-container{
    max-width:1600px !important;
    background:
    linear-gradient(
        135deg,
        #0f172a,
        #111827,
        #1e293b
    );
}

.hero{
    padding:50px 40px;
    border-radius:25px;
    background:
    linear-gradient(
        120deg,
        rgba(99,102,241,0.15),
        rgba(255,255,255,0.04)
    );
    border: 1px solid rgba(255,255,255,0.08);
    backdrop-filter: blur(12px);
    color:white;
    text-align:center;
    margin-bottom:20px;
    box-shadow: 0 0 40px rgba(99,102,241,0.15);
}

.hero h1{
    font-size:42px;
    font-weight:800;
    margin:0;
    background: linear-gradient(90deg, #818cf8, #38bdf8, #34d399);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
    letter-spacing: 1px;
}

.hero h3{
    font-weight:400;
    color:#cbd5e1;
    margin-top:6px;
    letter-spacing:0.5px;
}

.hero p{
    color:#94a3b8;
    margin-top:12px;
    font-size:14px;
}

.kpi-grid{
    display:grid;
    grid-template-columns: repeat(4,1fr);
    gap:15px;
}

.kpi-card{
    background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius:20px;
    padding:24px 18px;
    text-align:center;
    color:white;
    transition: transform 0.25s ease, box-shadow 0.25s ease;
}

.kpi-card:hover{
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(99,102,241,0.25);
}

.kpi-icon{
    font-size:22px;
    display:block;
    margin-bottom:6px;
    opacity:0.85;
}

.kpi-card h2{
    margin:4px 0;
    font-size:28px;
    font-weight:700;
}

.kpi-card p{
    margin:0;
    color:#94a3b8;
    font-size:13px;
    letter-spacing:0.5px;
}

.status-pass h2{ color:#34d399; }
.status-warn h2{ color:#fbbf24; }
.status-fail h2{ color:#f87171; }

.section-card{
    background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.08);
    border-radius:20px;
    padding:20px;
    color:white;
}

"""

# ==========================================================
# APP START
# ==========================================================

with gr.Blocks(css=css, theme=gr.themes.Soft()) as app:

    gr.HTML("""

    <div class="hero">
        <h1>⚡ CODEWIRE PRO</h1>
        <h3>Engineering Compliance Hub</h3>
        <p>
        Voltage Analysis • Cable Sizing • Conduit Design •
        Box Fill • Ampacity • Executive Reports
        </p>
    </div>

    """)

    dashboard_cards = gr.HTML(value=generate_kpi_cards(94, "PASS", "10 AWG", "1.8%"))

    gr.Markdown("# Executive Dashboard")

    health_chart = gr.Plot(value=create_health_gauge())

    # ------------------------------------------------------
    # KPI STATUS
    # ------------------------------------------------------

    with gr.Row():
        score_box = gr.Textbox(label="Health Score", value="94")
        status_box = gr.Textbox(label="Compliance Status", value="PASS")
        wire_box = gr.Textbox(label="Recommended Wire", value="10 AWG")

    # ------------------------------------------------------
    # VOLTAGE ANALYSIS FUNCTION
    # ------------------------------------------------------

    def voltage_analysis(voltage, current, length, resistance):

        if voltage <= 0:
            return (
                "<h2>Invalid Voltage</h2>",
                create_health_gauge(0),
                "0",
                "FAIL",
                "-",
                generate_kpi_cards(0, "FAIL", "-", "0%")
            )

        drop = (2 * current * length * resistance) / 1000
        percent = (drop / voltage) * 100
        score, status = calculate_score(percent)

        if current <= 10:
            wire = "14 AWG"
        elif current <= 16:
            wire = "12 AWG"
        elif current <= 25:
            wire = "10 AWG"
        elif current <= 35:
            wire = "8 AWG"
        else:
            wire = "6 AWG"

        report = f"""

        <div class='section-card'>
            <h2>⚡ Voltage Analysis</h2>
            <p>Voltage Drop: {drop:.2f} V</p>
            <p>Loss: {percent:.2f} %</p>
            <p>Status: {status}</p>
        </div>

        """

        kpi_html = generate_kpi_cards(score, status, wire, f"{percent:.2f}%")

        return (report, create_health_gauge(score), str(score), status, wire, kpi_html)

    # ------------------------------------------------------
    # WIRE SIZING FUNCTION
    # ------------------------------------------------------

    def wire_sizing(current):

        if current <= 10:
            wire = "14 AWG (1.5 mm²)"
        elif current <= 16:
            wire = "12 AWG (2.5 mm²)"
        elif current <= 25:
            wire = "10 AWG (4 mm²)"
        elif current <= 35:
            wire = "8 AWG (6 mm²)"
        else:
            wire = "6 AWG (10 mm²)"

        return f"""

        <div class='section-card'>
            <h2>🔌 Recommended Wire</h2>
            <h1>{wire}</h1>
        </div>

        """

    # ------------------------------------------------------
    # VOLTAGE ANALYSIS UI
    # ------------------------------------------------------

    with gr.Accordion("⚡ Voltage Analysis", open=True):

        voltage = gr.Number(value=230, label="Voltage")
        current = gr.Number(value=18, label="Current")
        length = gr.Number(value=50, label="Length")
        resistance = gr.Number(value=0.5, label="Resistance")

        voltage_output = gr.HTML()

        run_voltage = gr.Button("Run Voltage Analysis")

        run_voltage.click(
            voltage_analysis,
            [voltage, current, length, resistance],
            [voltage_output, health_chart, score_box, status_box, wire_box, dashboard_cards]
        )

    # ------------------------------------------------------
    # WIRE SIZING UI
    # ------------------------------------------------------

    with gr.Accordion("🔌 Wire Sizing", open=False):

        wire_current = gr.Number(value=20, label="Load Current")
        wire_output = gr.HTML()
        wire_btn = gr.Button("Recommend Wire")

        wire_btn.click(wire_sizing, wire_current, wire_output)

    # ------------------------------------------------------
    # CONDUIT DESIGN
    # ------------------------------------------------------

    def conduit_design(wires):

        fill = wires * 12

        if fill <= 40:
            conduit = "1/2 inch"
        elif fill <= 60:
            conduit = "3/4 inch"
        elif fill <= 80:
            conduit = "1 inch"
        else:
            conduit = "1.25 inch+"

        fig = px.bar(x=["Fill %"], y=[fill], title="Conduit Utilization")
        fig.update_layout(template="plotly_dark", height=350)

        report = f"""

        <div class='section-card'>
            <h2>📦 Conduit Design</h2>
            <p>Fill Percentage: {fill}%</p>
            <p>Recommended Conduit: {conduit}</p>
        </div>

        """

        return report, fig

    # ------------------------------------------------------
    # BOX FILL
    # ------------------------------------------------------

    def box_fill(conductors, devices, grounds):

        volume = (conductors * 2) + (devices * 2) + grounds

        return f"""

        <div class='section-card'>
            <h2>📐 Box Fill Analysis</h2>
            <h1>{volume}</h1>
            <p>Required Volume Units</p>
        </div>

        """

    # ------------------------------------------------------
    # AMPACITY
    # ------------------------------------------------------

    def ampacity(size):

        table = {
            "14 AWG": 15,
            "12 AWG": 20,
            "10 AWG": 30,
            "8 AWG": 40,
            "6 AWG": 55
        }

        return f"""

        <div class='section-card'>
            <h2>🔥 Ampacity</h2>
            <h1>{table.get(size)} A</h1>
        </div>

        """

    # ------------------------------------------------------
    # MATERIAL ESTIMATOR
    # ------------------------------------------------------

    def material_estimator(length):

        wire_required = length * 1.10
        conduit_required = length

        fig = px.pie(
            names=["Wire", "Conduit"],
            values=[wire_required, conduit_required],
            hole=0.65
        )

        fig.update_layout(
            template="plotly_dark",
            title="Material Breakdown",
            height=400
        )

        report = f"""

        <div class='section-card'>
            <h2>📋 Material Estimate</h2>
            <p>Wire Required: {wire_required:.2f} m</p>
            <p>Conduit Required: {conduit_required:.2f} m</p>
        </div>

        """

        return report, fig

    # ------------------------------------------------------
    # CONDUIT UI
    # ------------------------------------------------------

    with gr.Accordion("📦 Conduit Design", open=False):

        conduit_wires = gr.Number(value=5, label="Number of Wires")
        conduit_output = gr.HTML()
        conduit_chart = gr.Plot()
        conduit_btn = gr.Button("Analyze Conduit")

        conduit_btn.click(
            conduit_design,
            conduit_wires,
            [conduit_output, conduit_chart]
        )

    # ------------------------------------------------------
    # BOX FILL UI
    # ------------------------------------------------------

    with gr.Accordion("📐 Box Fill", open=False):

        conductors = gr.Number(value=8, label="Conductors")
        devices = gr.Number(value=2, label="Devices")
        grounds = gr.Number(value=1, label="Grounds")

        box_output = gr.HTML()
        box_btn = gr.Button("Calculate Box Fill")

        box_btn.click(
            box_fill,
            [conductors, devices, grounds],
            box_output
        )

    # ------------------------------------------------------
    # AMPACITY UI
    # ------------------------------------------------------

    with gr.Accordion("🔥 Ampacity", open=False):

        ampacity_size = gr.Dropdown(
            ["14 AWG", "12 AWG", "10 AWG", "8 AWG", "6 AWG"],
            value="12 AWG",
            label="Wire Size"
        )

        ampacity_output = gr.HTML()
        ampacity_btn = gr.Button("Check Ampacity")

        ampacity_btn.click(ampacity, ampacity_size, ampacity_output)

    # ------------------------------------------------------
    # MATERIAL ESTIMATOR UI
    # ------------------------------------------------------

    with gr.Accordion("📋 Material Estimator", open=False):

        material_length = gr.Number(value=50, label="Cable Length (m)")
        material_output = gr.HTML()
        material_chart = gr.Plot()
        material_btn = gr.Button("Estimate Materials")

        material_btn.click(
            material_estimator,
            material_length,
            [material_output, material_chart]
        )

    # ------------------------------------------------------
    # COMPLIANCE DONUT CHART
    # ------------------------------------------------------

    def compliance_donut(score):

        fig = go.Figure(
            data=[
                go.Pie(
                    labels=["Compliance", "Remaining"],
                    values=[score, 100 - score],
                    hole=0.75
                )
            ]
        )

        fig.update_layout(
            template="plotly_dark",
            height=400,
            title="Compliance Meter"
        )

        return fig

    # ------------------------------------------------------
    # EXECUTIVE SUMMARY
    # ------------------------------------------------------

    def executive_summary(score, status, wire):

        return f"""

        <div class='section-card'>
            <h2>Executive Summary</h2>
            <hr>
            <p>Health Score: <b>{score}</b></p>
            <p>Compliance Status: <b>{status}</b></p>
            <p>Recommended Wire: <b>{wire}</b></p>
            <p>Generated: <b>{datetime.now().strftime('%d-%m-%Y')}</b></p>
        </div>

        """

    # ------------------------------------------------------
    # DASHBOARD ANALYTICS
    # ------------------------------------------------------

    with gr.Accordion("📊 Executive Analytics", open=False):

        with gr.Row():

            with gr.Column(scale=1):
                analytics_chart = gr.Plot(value=compliance_donut(94))

            with gr.Column(scale=1):
                analytics_summary = gr.HTML(
                    value=executive_summary("94", "PASS", "10 AWG")
                )

    # ------------------------------------------------------
    # LIVE DASHBOARD REFRESH
    # ------------------------------------------------------

    def refresh_dashboard(score, status, wire):

        return (
            compliance_donut(int(score)),
            executive_summary(score, status, wire),
            generate_kpi_cards(score, status, wire, "—")
        )

    dashboard_refresh_btn = gr.Button("🔄 Refresh Dashboard")

    dashboard_refresh_btn.click(
        refresh_dashboard,
        [score_box, status_box, wire_box],
        [analytics_chart, analytics_summary, dashboard_cards]
    )

    # ------------------------------------------------------
    # PROJECT SAVE FUNCTION
    # ------------------------------------------------------

    def save_project(project_name, score, status, wire):

        if not project_name:
            return ("❌ Enter Project Name", "")

        projects[project_name] = {
            "score": score,
            "status": status,
            "wire": wire,
            "date": datetime.now().strftime("%d-%m-%Y %H:%M")
        }

        project_list = "\n".join(projects.keys())

        return (f"✅ Project '{project_name}' Saved", project_list)

    # ------------------------------------------------------
    # LOAD PROJECT
    # ------------------------------------------------------

    def load_project(project_name):

        if project_name not in projects:
            return ("0", "NOT FOUND", "-", generate_kpi_cards(0, "FAIL", "-", "—"))

        data = projects[project_name]

        return (
            data["score"],
            data["status"],
            data["wire"],
            generate_kpi_cards(data["score"], data["status"], data["wire"], "—")
        )

    # ------------------------------------------------------
    # PROJECT MANAGER UI
    # ------------------------------------------------------

    with gr.Accordion("📂 Project Manager", open=False):

        project_name = gr.Textbox(
            label="Project Name",
            placeholder="Enter Project Name"
        )

        save_status = gr.Textbox(label="Status")
        project_history = gr.Textbox(label="Saved Projects")

        with gr.Row():
            save_btn = gr.Button("💾 Save Project")
            load_btn = gr.Button("📂 Load Project")

        save_btn.click(
            save_project,
            [project_name, score_box, status_box, wire_box],
            [save_status, project_history]
        )

        load_btn.click(
            load_project,
            project_name,
            [score_box, status_box, wire_box, dashboard_cards]
        )

    # ------------------------------------------------------
    # PDF GENERATOR
    # ------------------------------------------------------

    def generate_pdf_report(project_name, score, status, wire):

        if not project_name:
            project_name = "CodeWire_Report"

        filename = project_name.replace(" ", "_") + ".pdf"

        doc = SimpleDocTemplate(filename)
        styles = getSampleStyleSheet()

        content = [
            Paragraph("CODEWIRE PRO", styles["Title"]),
            Spacer(1, 12),
            Paragraph("Engineering Compliance Report", styles["Heading2"]),
            Spacer(1, 12),
            Paragraph(f"<b>Project:</b> {project_name}", styles["BodyText"]),
            Paragraph(f"<b>Date:</b> {datetime.now()}", styles["BodyText"]),
            Spacer(1, 12),
            Paragraph(f"<b>Health Score:</b> {score}", styles["BodyText"]),
            Paragraph(f"<b>Status:</b> {status}", styles["BodyText"]),
            Paragraph(f"<b>Recommended Wire:</b> {wire}", styles["BodyText"]),
            Spacer(1, 20),
            Paragraph("Executive Summary", styles["Heading2"]),
            Paragraph(
                """
                This report was generated using CodeWire Pro V2.
                Engineering calculations were completed successfully.
                Review all electrical installations before final implementation.
                """,
                styles["BodyText"]
            )
        ]

        doc.build(content)

        return filename

    # ------------------------------------------------------
    # REPORTS UI
    # ------------------------------------------------------

    with gr.Accordion("📄 Executive Reports", open=False):

        pdf_file = gr.File(label="Download Report")
        pdf_btn = gr.Button("📄 Generate PDF Report")

        pdf_btn.click(
            generate_pdf_report,
            [project_name, score_box, status_box, wire_box],
            pdf_file
        )

    # ------------------------------------------------------
    # FOOTER
    # ------------------------------------------------------

    gr.HTML("""

    <hr>

    <center>
    <h3>⚡ CODEWIRE PRO V2</h3>
    <p>Engineering Compliance Hub</p>
    <p>Built with Gradio + Plotly</p>
    </center>

    """)

# ==========================================================
# APP LAUNCH
# ==========================================================

app.launch(share=True)